[package]
name = "CodeWars-rust-cgdk"
version = "0.1.0"
authors = ["elsid <elsid.mail@gmail.com>"]

[dependencies]
argparse = "0.2.1"
byteorder = "1.1.0"

[[bin]]
name = "code_wars"
path = "src/code_wars/main.rs"
